### ISSUE TITLE
Flatpack error on Debian Bookworm

### ISSUE THREAD

**Issue by canonex** [dlippok/photometric-viewer#133]
On Debian Bookworm the flatpack does not start.
Testing it from the command line I receive the following error.
Thank you,
Riccardo

`flatpak run io.github.dlippok.photometric-viewer`

```
Traceback (most recent call last):
  File "/app/bin/photometric-viewer", line 5, in <module>
    from photometric_viewer.main import run
  File "/app/lib/python3.10/site-packages/photometric_viewer/main.py", line 10, in <module>
    from photometric_viewer.gui.window import MainWindow
  File "/app/lib/python3.10/site-packages/photometric_viewer/gui/window.py", line 20, in <module>
    from photometric_viewer.gui.pages.content import PhotometryContentPage
  File "/app/lib/python3.10/site-packages/photometric_viewer/gui/pages/content.py", line 4, in <module>
    from photometric_viewer.gui.pages.base import BasePage
  File "/app/lib/python3.10/site-packages/photometric_viewer/gui/pages/base.py", line 7, in <module>
    class BasePage(Adw.NavigationPage):
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'NavigationPage'
```

**Comment by canonex** [comment]
Thank you, the viewer is now working.
Very nice, thank you!
